### ISSUE TITLE
Slack link outdated

### ISSUE THREAD

**Issue by mhellmeier** [standardnotes/docs#19]
The link to the Slack group on the following page is outdated:
https://github.com/standardnotes/docs/blob/main/docs/extensions/publishing.md#questions

**Comment by JaspalSuri** [comment]
Hi @mhellmeier,

We'll update the link soon! It appears that a new link must be provided every 30 days as of a recent change made by the Slack team (so if it happens to break again, that's why). 

[Here is the new invite link](https://join.slack.com/t/standardnotes/shared_invite/zt-lrvhtzms-_uM66B1IuT67WApDtxxSLA); please let us know if that work for you. 🙂

**Comment by mhellmeier** [comment]
Great, thanks!

I found out that the Slack link is also present on other pages in the documentation (so same problem exists).

> It appears that a new link must be provided every 30 days as of a recent change made by the Slack team (so if it happens to break again, that's why).

Perhaps you can create a link in your infastructure that will be added to all documentation pages and redircts to the current Slack invitation link, like https://docs.standardnotes.org/invite-slack --> https://standardnotes.slack.com/join/shared_invite/[...]
Thus, you can change the redirection from https://docs.standardnotes.org/invite-slack every 30 days without touching all documentation pages every month.

**Comment by theodorechu** [comment]
Hi @mhellmeier,

Thanks for pointing out that our Slack invitation link is outdated.

> Perhaps you can create a link in your infastructure that will be added to all documentation pages and redircts to the current Slack invitation link, like https://docs.standardnotes.org/invite-slack --> https://standardnotes.slack.com/join/shared_invite/[...]
Thus, you can change the redirection from https://docs.standardnotes.org/invite-slack every 30 days without touching all documentation pages every month.

We currently do this. The link https://standardnotes.org/slack redirects to a slack.com invitation link and is used in the doc that you linked above.
