### ISSUE TITLE
How to get a dock icon for your theme

### ISSUE THREAD

**Issue by atmoio** [standardnotes/docs#5]
This should be added to the documentation:

In order to get SN to display a dock icon for your theme (a circle in the lower right corner of the app that allows you to quickly toggle themes), add the following payload into the your `ext.json` file:

``` json
"dock_icon": {
   "type": "circle",
   "background_color": "#086DD6",
   "foreground_color": "#ffffff",
   "border_color": "#086DD6"
}
```

**Comment by theodorechu** [comment]
Done here: https://github.com/standardnotes/docs/commit/0ed2741800833d858c0a9e6249907d287c7f0697
