### ISSUE TITLE
Clarifying the `area` property for components in ext.json

### ISSUE THREAD

**Issue by ningsongshen** [standardnotes/docs#7]
When users set up an extension locally (https://docs.standardnotes.org/extensions/local-setup), there can be some confusion (or just misreading) around what should go under the `area` property in `ext.json`. Many just leave the default value, and thus extensions like Folders or Action Bar don't work properly when setup. This occurred to me as well, and I had to do some digging to determine the correct values to use for a given component. 

I propose adding a diagram to the aforementioned page under step 4; something like the below would make things crystal clear. Although it would have to be more professional-looking and polished.

![image](https://user-images.githubusercontent.com/12574693/86031413-ca4e0380-ba03-11ea-8ea4-669b3bf0172c.png)

In addition, (perhaps) more emphasis should be placed on the `url` and `area` properties because those are the important ones that affect the normal function of extensions.

cc @mobitar @TheodoreChu @zsoltszilvai

**Comment by theodorechu** [comment]
The different options for Area are described [here](https://docs.standardnotes.org/extensions/building-an-extension#available-areas), but you're right that a picture may help and we could be more clear on the local-setup page. It would also help to explain what should go under `content_type`

**Comment by atmoio** [comment]
Great idea, the diagram really helps quickly communicate this!

**Comment by theodorechu** [comment]
I added the diagram to https://docs.standardnotes.org/extensions/building-an-extension#available-areas

**Comment by theodorechu** [comment]
Thanks for the suggestion and the diagram @ningsongshen! 😄
